In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


# Conda prepare environment

In [2]:
# Unset PYTHONPATH before installing minicoda, otherwise it may cause issues
%env PYTHONPATH=

env: PYTHONPATH=


In [3]:
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

PREFIX=/usr/local
installing: python-3.6.5-hc3d631a_2 ...
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-hdf63c60_3 ...
installing: libstdcxx-ng-7.2.0-hdf63c60_3 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2o-h20670df_0 ...
installing: tk-8.6.7-hc745277_3 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-ha6073c6_4 ...
installing: sqlite-3.23.1-he433501_0 ...
installing: asn1crypto-0.24.0-py36_0 ...
installing: certifi-2018.4.16-py36_0 ...
installing: chardet-3.0.4-py36h0f667ec_1 ...
installing: idna-2.6-py36h82fb2a8_1 ...
installing: pycosat-0.6.3-py36h0a5515d_0 ...
installing: pycparser-2.18-py36hf9f622e_1 ...
installing: pysocks-1.6.8-py36_0 ...
installing: ruamel_yaml-0.15.37-py36h14c3975_2 ...
installing: six-1.11

--2021-09-19 08:39:20--  https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh [following]
--2021-09-19 08:39:20--  https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58468498 (56M) [application/x-sh]
Saving to: ‘Miniconda3-4.5.4-Linux-x86_64.sh’

     0K .......... .......... .......... .......... ..........  0% 4.79M 12s
    50K .......... .......... .......... .......... ..........  0

In [4]:
%%bash
conda install --channel defaults conda python=3.7 --yes
conda update --channel defaults --all --yes

Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local

  added / updated specs: 
    - conda
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyopenssl-20.0.1           |     pyhd3eb1b0_1          48 KB
    pysocks-1.7.1              |           py37_1          27 KB
    zlib-1.2.11                |       h7b6447c_3         120 KB
    conda-4.10.3               |   py37h06a4308_0         3.1 MB
    openssl-1.1.1l             |       h7f8727e_0         3.8 MB
    cffi-1.14.6                |   py37h400218f_0         224 KB
    yaml-0.2.5                 |       h7b6447c_0          87 KB
    charset-normalizer-2.0.4   |     pyhd3eb1b0_0          33 KB
    ncurses-6.2                |       he6710b0_1         1.1 MB
    xz-5.2.5                   |       h7b6447c_0         438 KB
    requests-2.26.0            |     pyhd3eb1b0_0   

pyopenssl-20.0.1     |   48 KB | ########## | 100% 
pysocks-1.7.1        |   27 KB | ########## | 100% 
zlib-1.2.11          |  120 KB | ########## | 100% 
conda-4.10.3         |  3.1 MB | ########## | 100% 
openssl-1.1.1l       |  3.8 MB | ########## | 100% 
cffi-1.14.6          |  224 KB | ########## | 100% 
yaml-0.2.5           |   87 KB | ########## | 100% 
charset-normalizer-2 |   33 KB | ########## | 100% 
ncurses-6.2          |  1.1 MB | ########## | 100% 
xz-5.2.5             |  438 KB | ########## | 100% 
requests-2.26.0      |   59 KB | ########## | 100% 
tqdm-4.62.2          |   93 KB | ########## | 100% 
ca-certificates-2021 |  119 KB | ########## | 100% 
python-3.7.11        | 52.9 MB | ########## | 100% 
libgcc-ng-9.1.0      |  8.1 MB | ########## | 100% 
setuptools-58.0.4    |  979 KB | ########## | 100% 
pip-21.2.2           |  2.0 MB | ########## | 100% 
libstdcxx-ng-9.1.0   |  4.0 MB | ########## | 100% 
sqlite-3.36.0        |  1.4 MB | ########## | 100% 
ruamel_yaml-

In [5]:
import sys
_ = (sys.path
        .append("/usr/local/lib/python3.7/site-packages"))

In [6]:
!conda config --append channels conda-forge

!conda create --name scipydev python=3.7 numpy pybind11 cython pythran pytest gfortran_linux-64 gxx_linux-64 sphinx pydata-sphinx-theme sphinx-panels matplotlib mypy git --yes

Solving environment: | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / done

## Package Plan ##

  environment location: /usr/local/envs/scipydev

  added / updated specs:
    - cython
    - gfortran_linux-64
    - git
    - gxx_linux-64
    - matplotlib
    - mypy
    - numpy
    - pybind11
    - pydata-sphinx-theme
    - pytest
    - python=3.7
    - pythran
    - sphinx
    - sphinx-panels


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            1_gnu          22 KB  conda-forge
    alabaster-0.7.12           |           py37_0          18 KB
    attrs-21.2.0               |     pyhd3eb1b0_0          46 KB
    ba

In [7]:
!conda install conda-build --yes

Solving environment: | / - \ | / - \ | / - \ | / - \ | / - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::asn1crypto==0.24.0=py36_0
  - defaults/linux-64::chardet==3.0.4=py36h0f667ec_1
\ | / - \ | done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - conda-build


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asn1crypto-1.4.0           |             py_0          80 KB
    chardet-4.0.0              |py37h06a4308_1003         195 KB
    conda-build-3.21.5         |   py37h06a4308_0         549 KB
    filelock-3.0.12            |     pyhd3eb1b0_1          10 KB
    glob2-0.7                  |     pyhd3eb1b0_0          12 KB
    jinja2-2.11.3              |     pyhd3eb1b0_0         101 KB
    lib

In [8]:
%%bash
source activate scipydev

conda install pandas scikit-learn --yes

Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local/envs/scipydev

  added / updated specs:
    - pandas
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bottleneck-1.3.2           |   py37heb32a55_1         125 KB
    joblib-1.0.1               |     pyhd3eb1b0_0         208 KB
    libblas-3.9.0              |   11_linux64_mkl          12 KB  conda-forge
    libcblas-3.9.0             |   11_linux64_mkl          11 KB  conda-forge
    libgfortran-ng-9.3.0       |      ha5ec8a7_17          22 KB
    liblapack-3.9.0            |   11_linux64_mkl          11 KB  conda-forge
    numexpr-2.7.3              |   py37h22e1b3c_1         188 KB
    pandas-1.3.2               |   py37h8c16a72_0         9.2 MB
    scikit-learn-0.24.2        |   py37ha9443f7_0         5.2 MB
    scipy-1.6.3                |   py37h29e03ee_0        20.5 

In [9]:
%%bash
source activate scipydev

conda install -c plotly plotly --yes

Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local/envs/scipydev

  added / updated specs:
    - plotly


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    plotly-5.3.1               |             py_0         6.8 MB  plotly
    tenacity-6.3.1             |   py37h06a4308_0          36 KB
    ------------------------------------------------------------
                                           Total:         6.8 MB

The following NEW packages will be INSTALLED:

  plotly             plotly/noarch::plotly-5.3.1-py_0
  tenacity           pkgs/main/linux-64::tenacity-6.3.1-py37h06a4308_0



plotly-5.3.1         | 6.8 MB    | ########## | 100% 
tenacity-6.3.1       | 36 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


# Global configuration

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib

from scipy.cluster.hierarchy import dendrogram, linkage, fcluster, inconsistent
from scipy.spatial.distance import cdist, pdist
from sklearn import preprocessing
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import matplotlib.pyplot as plt
%matplotlib inline

algo = "HC"
base_path = "/content/drive/MyDrive/MIDA2/IntelligentMobilityProject/"
pictures_path = f"{base_path}Pictures/"
dataset_path = f"{base_path}Survey+dataset/"
code_path = f"{base_path}Code/"
results_path = f"{base_path}Code/Data/"
HC_base_path = f"{results_path}{algo}/"
numpy_file_type = ".npy"
image_file_type = ".html"

radars_path = f'{pictures_path}RadarCharts/'

import sys
sys.path.append(code_path)
np.set_printoptions(precision=5, suppress=True)

# DNA selection (params here)

In [12]:
metric = 'VDM'

In [13]:
ds_path = f'{dataset_path}3_filtered_values.csv'

df = pd.read_csv(ds_path)

In [14]:
df.columns

Index(['Country', 'Gender', 'Education', 'Profession', 'Work_status',
       'Household_members', 'Income_level', 'Location_of_resudence',
       'Centre_or_suburbs', 'Public_transport_service', 'Car_driving_license',
       'Considering_electric_or_hybrid_vehicle_next_purchase',
       'Know_what_car_sharing_is', 'Would_subsribe_car_sharing_if_available',
       'Most_frequent_trip_Walk', 'Most_frequent_trip_Bicycle',
       'Most_frequent_trip_Car_as_Driver',
       'Most_frequent_trip_Car_as_Passenger', 'Most_frequent_trip_Train',
       'Most_frequent_trip_Underground_or_light_train',
       'Most_frequent_trip_Tram', 'Most_frequent_trip_Bus',
       'Most_frequent_trip_Motorcycle_or_moped',
       'Destination_most_frequent_trip', 'Frequency_most_frequent_trip',
       'Frequent_trip_distance', 'Concern_environmental_impacts',
       'Preference_tolls_or_traffic_limitation',
       'grouped_Frequent_trip_duration_in_minutes', 'grouped_Region_3',
       'InternetUsers', 'grouped_Nu

In [15]:
columns = [
  "InternetUsers",
  "Concern_environmental_impacts",
  "Would_subsribe_car_sharing_if_available", 
  "Preference_tolls_or_traffic_limitation",
  "Country",
  "Location_of_resudence",
  "Considering_electric_or_hybrid_vehicle_next_purchase",
]

metric = 'VDM'
save_ds = True
vars = len(columns)-1

if metric == 'VDM':
  categorical_ix = [i for i in range(vars)]
else:
  categorical_ix = [i for i in range(2, vars)]

df_DNA = df[columns]

In [16]:
df_DNA

InternetUsers  ... Considering_electric_or_hybrid_vehicle_next_purchase
0                 75  ...                                Maybe yes maybe not  
1                 71  ...                                       Probably not  
2                 63  ...                                      Certainly not  
3                 85  ...                                Maybe yes maybe not  
4                 50  ...                                       Probably yes  
...              ...  ...                                                ...  
26600             63  ...                               Don't know/no answer  
26601             63  ...                               Don't know/no answer  
26602             63  ...                                Maybe yes maybe not  
26603             63  ...                                       Probably yes  
26604             63  ...                                Maybe yes maybe not  

[26605 rows x 7 columns]

# Radar Chart variable value mappings

In [17]:
cleanup_nums = {"Concern_environmental_impacts":
                {
                    '1': 0,
                    '2': 1,
                    '3': 2,
                    '4': 3,
                    '5': 4,
                    "Don't know": 5,
                    '6': 6,
                    '7': 7,
                    '8': 8,
                    '9': 9,
                    '10': 10 
                 },
                "Would_subsribe_car_sharing_if_available":
                { # no should weigh 4
                    'No, I would not be interested in this service': 0.,
                    "Don't know / No answer": .45,
                    'Maybe yes, maybe not. I would need to test the service before taking a decision': 0.55,
                    'Yes without any influence on my car ownership': 0.7,
                    'Yes, instead of purchasing a new car': 0.8,
                    'Yes and I would give up one car I currently own': 0.9,
                    "Yes I'm already client of a car sharing service": 1.
                },
                "Preference_tolls_or_traffic_limitation":
                {
                    'Definitely more acceptable to pay for less congestion': 0.,
                    'Probably more acceptable to pay for less congestion': 0.25,
                    'No preferences': 0.5,
                    'Probably more acceptable to limit road traffic': 0.75,
                    'Definitely more acceptable to limit road traffic': 1.,
                },
                #"Considering_electric_or_hybrid_vehicle_next_purchase":
                #{
                #    'Certainly not':0,
                #    'Probably not':1,                   
                #    "Don't know/no answer":2,
                #    'Maybe yes maybe not':3,
                #    'Probably yes':4,
                #    'Certainly yes':5,
                #},
                "Location_of_resudence":
                {
                    'Rural area': 0.,
                    'Small or medium town (less than 250.000 inhabitants)': 0.33,
                    'Large city (from 250.000 to 1.000.000 inhabitants)': 0.66, 
                    'Metropolitan area of a big city with more than 1.000.000  inhabitants': 1.,
                }
}

In [18]:
numerical_cols = ["InternetUsers", 
                  "Concern_environmental_impacts",
                  "Would_subsribe_car_sharing_if_available", 
                  "Preference_tolls_or_traffic_limitation"]
if len(df_DNA.columns) == 7:
  numerical_cols.append("Location_of_resudence")

categorical_cols = ["Country"]
target_col = "Considering_electric_or_hybrid_vehicle_next_purchase"
df_numerical = df_DNA[numerical_cols]

In [19]:
df_numerical = df_numerical.replace(cleanup_nums)
df = df_DNA.copy()
df[numerical_cols] = df_numerical
df

InternetUsers  ...  Considering_electric_or_hybrid_vehicle_next_purchase
0                 75  ...                                Maybe yes maybe not   
1                 71  ...                                       Probably not   
2                 63  ...                                      Certainly not   
3                 85  ...                                Maybe yes maybe not   
4                 50  ...                                       Probably yes   
...              ...  ...                                                ...   
26600             63  ...                               Don't know/no answer   
26601             63  ...                               Don't know/no answer   
26602             63  ...                                Maybe yes maybe not   
26603             63  ...                                       Probably yes   
26604             63  ...                                Maybe yes maybe not   

[26605 rows x 7 columns]

In [20]:
true_numerical_cols = ["InternetUsers", "Concern_environmental_impacts"]
x = df[true_numerical_cols].values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_numerical = pd.DataFrame(x_scaled)
df_numerical.columns = true_numerical_cols

In [21]:
df[true_numerical_cols] = df_numerical
df

InternetUsers  ...  Considering_electric_or_hybrid_vehicle_next_purchase
0           0.758621  ...                                Maybe yes maybe not   
1           0.689655  ...                                       Probably not   
2           0.551724  ...                                      Certainly not   
3           0.931034  ...                                Maybe yes maybe not   
4           0.327586  ...                                       Probably yes   
...              ...  ...                                                ...   
26600       0.551724  ...                               Don't know/no answer   
26601       0.551724  ...                               Don't know/no answer   
26602       0.551724  ...                                Maybe yes maybe not   
26603       0.551724  ...                                       Probably yes   
26604       0.551724  ...                                Maybe yes maybe not   

[26605 rows x 7 columns]

In [22]:
metric_df_path = f'{dataset_path}4_DNA_{vars}values_normalized.csv'
metric_df = pd.read_csv(metric_df_path)

In [23]:
df_radar_normalized = df.drop(target_col, axis=1)
df_radar_normalized["Country"] = metric_df["Country"] # label encoding normalized
vars = len(df_radar_normalized.columns)
df_radar_normalized_path = f'{dataset_path}4_DNA_{vars}values_radar_normalized.csv'
df_radar_normalized.to_csv(df_radar_normalized_path, index=False)

In [24]:
some_path = f'{dataset_path}4_DNA_{vars}values_normalized.csv'
pd.read_csv(some_path)

InternetUsers  ...  Location_of_resudence
0           0.758621  ...               1.000000
1           0.689655  ...               0.333333
2           0.551724  ...               0.666667
3           0.931034  ...               1.000000
4           0.327586  ...               1.000000
...              ...  ...                    ...
26600       0.551724  ...               0.000000
26601       0.551724  ...               0.333333
26602       0.551724  ...               0.333333
26603       0.551724  ...               0.333333
26604       0.551724  ...               0.333333

[26605 rows x 6 columns]

# Plot all medoids of a merge

In [37]:
%%bash
source activate scipydev
cd /content/drive/MyDrive/MIDA2/IntelligentMobilityProject/Code/scipy

python
# --- import packages
import pandas as pd
import numpy as np
import sys

from scipy.cluster.hierarchy import dendrogram, linkage, fcluster, inconsistent
from scipy.spatial.distance import cdist, pdist, squareform

def vdm_prepare_df(df, cat_ix):
  replace_arr = {}
  for col in df.columns[~cat_ix]:
    replace_arr[col] = { value: key for key, value in enumerate(np.sort(df[col].unique()))}
  return df.replace(replace_arr)

def getMedoidVDM(vdm_df_cluster, df_cluster, metric):
  distance_matrix_cluster = squareform(pdist(vdm_df_cluster, metric=metric))
  distance_matrix_medoid_ix = np.argmin(distance_matrix_cluster.sum(axis=0))
  medoid = df_cluster.iloc[distance_matrix_medoid_ix]

  return medoid

# ------- config vars ---------
algo = "HC"
base_path = "/content/drive/MyDrive/MIDA2/IntelligentMobilityProject/"
pictures_path = f"{base_path}Pictures/"
dataset_path = f"{base_path}Survey+dataset/"
results_path = f"{base_path}Code/Data/"
HC_base_path = f"{results_path}{algo}/"
radars_path = f'{pictures_path}RadarCharts/'

sys.path.append(f"{base_path}Code")
from postprocessing.merge_cuts import merge_multiple_cuts
from plots.radar_charts import plot_all_medoids_radar
from metrics.silhouette import getSilhouette

metric="VDM"
file_type = ".npy"
wss_file_type = ".npy"
vars_values = [5,6]
linkages = ["single","complete", "average", "weighted"]
postprocessing_values = [False, True]

vars_linkage_cuts = {5:
                  {
                    "average":[[2,3,5,7,9],[2,3,5,7,9,12]],
                    "complete":[[2,4],[2,4,6],[2,4,6,8]],
                    "weighted":[[2,4,6,8],[2,4,6,8,11]],
                    "single":[[2,4,6,14,19,24,28,33,49,86]]
                  },
                  6:
                  {
                    "average": [[2,3,5,7,9]],
                    "complete":[[2,3,5]],
                    "weighted":[[2,4,6,8,11,13]],
                    "single":[[2,4,6,15,19,25,29,31,41,59,75,85,124]]
                  }
}

# ------- compute medoid -------
for vars in vars_values:
  print(f"vars: {vars} ...")
  # -------- load dataset ---------
  ds_path = f'{dataset_path}4_DNA_{vars}values_radar_normalized.csv'
  df = pd.read_csv(ds_path)

  if metric == 'VDM':
    cat_ix = np.array([i in range(2, vars) for i in range(vars)])
    vdm_df = vdm_prepare_df(df, cat_ix)

  try:
    del distance_matrix
  except:
    distance_matrix = []
  distance_matrix = np.load(f"{results_path}distance_matrix_{metric}{vars}.npy")
  
  for link in linkages:
    print(f"Link: {link} ...")
    # -------- load linkage and compute matrix --------
    HC_path = f"{HC_base_path}{metric}{vars}/{algo}_{metric}_{link}{file_type}"
    Z = {}
    Z[metric] = np.load(HC_path)

    for cut_values in vars_linkage_cuts[vars][link]:
      print(f"cut_values: {cut_values} ...")
      for postprocessing in postprocessing_values:
        print(f"postprocessing: {postprocessing} ...")
        is_postprocessing = "_fix" if postprocessing else ""
        print("Z:",Z[metric])
        print("cut_values:",cut_values)

        cluster_labels = merge_multiple_cuts(Z[metric], cut_values)
        if postprocessing:
          _, _, cluster_labels = getSilhouette(distance_matrix, cluster_labels, postprocessing)

        cluster_labels_path = f"{HC_base_path}{metric}{vars}/ClusterLabels/ClusterLabels_{metric}_{link}_{str(cut_values)}{is_postprocessing}.npy"
        np.save(cluster_labels_path, cluster_labels)
        vdm_df["cluster"] = cluster_labels
        df["cluster"] = cluster_labels

        cluster_values, cluster_labels_counts = np.unique(cluster_labels, return_counts=True)
        cluster_values, cluster_labels_counts = \
        cluster_values[cluster_values > 0], cluster_labels_counts[cluster_values > 0] # do not get outlier label
        print(cluster_values, cluster_labels_counts)
        medoids = []
        for i, cluster in enumerate(cluster_values):
          vdm_df_cluster = vdm_df.loc[vdm_df["cluster"]==cluster].drop("cluster", axis=1)
          df_cluster = df.loc[df["cluster"]==cluster]
          df_cluster = df_cluster.assign(cluster_count=cluster_labels_counts[i])
          medoid = getMedoidVDM(vdm_df_cluster, df_cluster, metric)
          medoids.append(medoid)
        medoids_df = pd.DataFrame(medoids)
        medoids_df["cluster"] = medoids_df["cluster"].astype(np.int64)
        medoids_df["cluster_count"] = medoids_df["cluster_count"].astype(np.int64)
        medoids_df = medoids_df.sort_values(by='cluster_count', ascending=False)
        medoids_paths = f"{HC_base_path}{metric}{vars}/Medoids/Medoids_{metric}_{link}_{str(cut_values)}{is_postprocessing}.csv"
        medoids_df.to_csv(medoids_paths, index=False)

        medoids_radar_paths = f"{radars_path}{metric}{vars}/Medoids/Medoids_{metric}_{link}_{str(cut_values)}{is_postprocessing}.html"
        plot_all_medoids_radar(medoids_df.drop("cluster_count", axis=1), medoids_df["cluster_count"].values, save_path=medoids_radar_paths)

vars: 5 ...
Link: single ...
cut_values: [2, 4, 6, 14, 19, 24, 28, 33, 49, 86] ...
postprocessing: False ...
Z: [[0.00000000e+00 4.20000000e+01 0.00000000e+00 2.00000000e+00]
 [3.60000000e+02 2.66050000e+04 0.00000000e+00 3.00000000e+00]
 [1.25300000e+03 2.66060000e+04 0.00000000e+00 4.00000000e+00]
 ...
 [5.31980000e+04 5.32040000e+04 3.46673499e-02 2.51190000e+04]
 [5.32000000e+04 5.32050000e+04 3.46673499e-02 1.48600000e+03]
 [5.32060000e+04 5.32070000e+04 1.28096762e-01 2.66050000e+04]]
cut_values: [2, 4, 6, 14, 19, 24, 28, 33, 49, 86]
max_split: 25119
[[    1   966]
 [    2 24153]]
[1 2]
k1(2): [1 2]
k2(4): [1 2]
[1] [1 2]
[1] [4 5]
max_split: 24153
[[    2 23639]
 [    3   514]]
[2 3]
k1(2): [2 4 5]
k2(6): [2 3]
[5] [2 3]
[5] [8 9]
max_split: 23639
[[    3  1401]
 [    4 22238]]
[3 4]
k1(2): [2 4 8 9]
k2(14): [3 4]
[8] [3 4]
[8] [13 14]
max_split: 22238
[[    5    92]
 [    6 22146]]
[6]
k1(2): [ 2  4  9 13 14]
k2(19): [6]
[14] [6]
[14] [21]
max_split: 22146
[[    8 22087]
 [    

tcmalloc: large alloc 5662613504 bytes == 0x55b9fd2ca000 @  0x7feed1bcb1e7 0x7feecf62498d 0x7feecf624a07 0x7feecf664eaa 0x7feecf6691c4 0x7feecf6fe36f 0x55b9f8faeb5c 0x55b9f8fe5240 0x55b9f90291bc 0x55b9f8f7dbb3 0x55b9f8f9e223 0x55b9f8fe50c5 0x55b9f90291bc 0x55b9f8f7dbb3 0x55b9f8f9e1c1 0x55b9f8fe50c5 0x55b9f902c602 0x55b9f8f7dbb3 0x55b9f8f7eee3 0x55b9f908c802 0x55b9f909694e 0x55b9f9096b3b 0x55b9f8f55b53 0x55b9f9097ccc 0x7feed0e04bf7 0x55b9f903c555
tcmalloc: large alloc 2225782784 bytes == 0x55bb91440000 @  0x7feed1bcd001 0x7feecf624a96 0x7feecf624b66 0x7feecf664e48 0x7feecf669047 0x7feecf6f9835 0x55b9f8faeb5c 0x55b9f8fe5240 0x55b9f90291bc 0x55b9f8f7dbb3 0x55b9f8f9e1c1 0x55b9f9028155 0x55b9f8f9dd17 0x55b9f9028155 0x55b9f8f7dbb3 0x55b9f8f7eee3 0x55b9f908c802 0x55b9f909694e 0x55b9f9096b3b 0x55b9f8f55b53 0x55b9f9097ccc 0x7feed0e04bf7 0x55b9f903c555
tcmalloc: large alloc 1729429504 bytes == 0x55bb82d36000 @  0x7feed1bcd001 0x7feecf624a96 0x7feecf624b66 0x7feecf664e48 0x7feecf669047 0x7feecf6f

## Test plot medoid radar

In [34]:
metric = "VDM"
vars = 5
link = "single"
cut_values = [2,4,6,14,19,24,28,33,49,86]
medoids_paths = f"{HC_base_path}{metric}{vars}/Medoids/Medoids_{metric}_{link}_{str(cut_values)}.csv"
medoids_df = pd.read_csv(medoids_paths)
medoids_df

InternetUsers  Concern_environmental_impacts  ...  cluster  cluster_count
0       0.500000                            0.7  ...       83        16680.0
1       0.500000                            0.8  ...       60         4046.0
2       0.500000                            0.8  ...        2         1486.0
3       0.603448                            0.7  ...       13         1401.0
4       0.448276                            0.5  ...        4          966.0
5       0.793103                            0.7  ...       42          882.0
6       0.448276                            0.0  ...        9          514.0
7       0.758621                            0.7  ...       59          479.0
8       0.724138                            0.8  ...       14           92.0
9       0.879310                            0.7  ...       21           59.0

[10 rows x 7 columns]

In [ ]:
import plotly.express as px
def plot_individual_radar(fig, polar_args, r, theta, index, row=1, col=1):
  fig.add_trace(go.Scatterpolar(
                        r=r,
                        theta=theta,
                        showlegend=False,
                        fill='toself',
                        line_color=px.colors.qualitative.Plotly[index%len(px.colors.qualitative.Plotly)]), 
                    row=row, col=col
                  )
  polar_args[f"polar{index}"] = dict(radialaxis=dict(visible=True,
                                                      range=[0.0, 1.0]
                                                      ),
                                     )

  return fig, polar_args

In [ ]:
def plot_all_medoids_radar(medoids_df, cluster_labels_counts, plot_cols=3,row_height=300, save_path=None):
  cols = plot_cols
  rows = int(np.ceil(medoids_df.shape[0]/cols))
  print(f"rows: {rows}, cols: {cols}")
  #radar_title = f"Radars of the most representative person in each cluster"
  titles = [str(i) for i in cluster_labels_counts] # get cluster size as title
  specs = [[{'type': 'polar'}]*cols]*rows
  fig = make_subplots(rows=rows, cols=cols,
                            specs=specs,
                            horizontal_spacing=0.3/cols,
                            vertical_spacing=0.4/rows,
                            subplot_titles=titles,
                            )
  polar_args = {}
  for i in range(rows):
    for j in range(cols):
      #print(f"plotting: {i+1},{j+1}. Index = {i*cols+j+1}")
      if i*cols+j < medoids_df.shape[0]:
        if medoids_df.drop("cluster", axis=1).shape[1] == 5:
          r = medoids_df.iloc[i*cols+j]
          theta = ["IUsers", "EnvImpact", "CarShare", "TollsTraffic"]
        elif medoids_df.drop("cluster", axis=1).shape[1] == 6:
          r = medoids_df.drop("Country", axis=1).iloc[i*cols+j]
          theta = ["IUsers", "EnvImpact", "CarShare", "TollsTraffic", "Residence"]
        fig, polar_args = plot_individual_radar(fig, polar_args, 
                                                r, theta, 
                                                index=i*cols+j+1,
                                                row=i+1,col=j+1)
  fig.update_layout(
    height=row_height*rows,
    **polar_args)
  
  # Fixing sublot title positioning:
  # https://stackoverflow.com/questions/65775407/can-you-alter-a-subplot-title-location-in-plotly
  fig.update_annotations(patch=dict(yshift=20)) 
  fig.show()

  if save_path:
    fig.write_html(save_path)

In [ ]:
medoids_df

InternetUsers  Concern_environmental_impacts  ...  Location_of_resudence  cluster
0       0.500000                            0.8  ...                   0.33      1.0
1       0.448276                            0.0  ...                   0.33      5.0
2       0.448276                            0.5  ...                   0.00     11.0
3       0.500000                            1.0  ...                   0.33     20.0
4       0.568966                            0.7  ...                   0.00     27.0
5       0.689655                            0.7  ...                   0.00     28.0

[6 rows x 7 columns]

In [ ]:
from postprocessing.merge_cuts import merge_multiple_cuts

In [ ]:
HC_path = f"{HC_base_path}{metric}{vars}/{algo}_{metric}_{link}.npy"
Z = {}
Z[metric] = np.load(HC_path)
cluster_labels = merge_multiple_cuts(Z[metric], cut_values)
_, cluster_labels_counts = np.unique(cluster_labels, return_counts=True)

k1: [1 2]
k2: [2, 3]
k1: [1 5 6]
k2: [4, 5]
k1: [ 1  5 11 12]
k2: [6, 7]
k1: [ 1  5 11 19 20]
k2: [6, 7]


In [ ]:
medoids_radar_paths = f"{radars_path}{metric}{vars}/Medoids/Medoids_{metric}_{link}_{str(cut_values)}.html"
plot_all_medoids_radar(medoids_df, cluster_labels_counts, save_path=medoids_radar_paths)#

rows: 2, cols: 3


# Plot medoids wrt Target

In [107]:
%%bash
source activate scipydev
cd /content/drive/MyDrive/MIDA2/IntelligentMobilityProject/Code/scipy

python
# --- import packages
import pandas as pd
import numpy as np
import sys
import os

from scipy.cluster.hierarchy import dendrogram, linkage, fcluster, inconsistent
from scipy.spatial.distance import cdist, pdist, squareform

def vdm_prepare_df(df, cat_ix):
  replace_arr = {}
  for col in df.columns[~cat_ix]:
    replace_arr[col] = { value: key for key, value in enumerate(np.sort(df[col].unique()))}
  return df.replace(replace_arr)


def target_sorter(column):
  """Sort function"""
  answers = ["Certainly not","Probably not", "Don't know/no answer",'Maybe yes maybe not',"Probably yes","Certainly yes"]
  correspondence = {answer: order for order, answer in enumerate(answers)}
  return column.map(correspondence)

# ------- config vars ---------
algo = "HC"
base_path = "/content/drive/MyDrive/MIDA2/IntelligentMobilityProject/"
pictures_path = f"{base_path}Pictures/"
dataset_path = f"{base_path}Survey+dataset/"
results_path = f"{base_path}Code/Data/"
HC_base_path = f"{results_path}{algo}/"
radars_path = f'{pictures_path}RadarCharts/'

sys.path.append(f"{base_path}Code")
from postprocessing.merge_cuts import merge_multiple_cuts
from plots.radar_charts import plot_all_medoids_radar
from metrics.silhouette import getSilhouette
from metrics.wss_bss import get_ith_medoid, getMedoidVDM

metric="VDM"
file_type = ".npy"
wss_file_type = ".npy"
vars_values = [5,6]
target = "Considering_electric_or_hybrid_vehicle_next_purchase"
target_class_types = ["multi","binary"]

# ------- compute medoid -------
for vars in vars_values:
  print(f"vars: {vars} ...")
  # -------- load dataset ---------
  ds_path = f'{dataset_path}4_DNA_{vars}values_radar_normalized.csv'
  df = pd.read_csv(ds_path)

  ds_target_path = f'{dataset_path}3_filtered_values.csv'
  df_target = pd.read_csv(ds_target_path)
  

  if metric == 'VDM':
    cat_ix = np.array([i in range(2, vars) for i in range(vars)])
    vdm_df = vdm_prepare_df(df, cat_ix)

  for target_class in target_class_types:
    print(f"******* target_class: {target_class}")
    if target_class == "binary":
      mask = ~df_target[target].isin(['Maybe yes maybe not', "Don't know/no answer"])
      df_target = df_target[mask]
      vdm_df = vdm_df[mask]
      df = df[mask]
      print("******No more maybes")
      target_map = {
          "Probably yes": "YES",
          "Certainly yes": "YES",
          "Probably not": "NO",
          "Certainly not": "NO",
      }
      print(df_target[target].unique())
      df_target[target] = df_target[target].replace(target_map)
      
    cluster_labels = df_target[target].values
    vdm_df["cluster"] = cluster_labels
    df["cluster"] = cluster_labels

    cluster_values, cluster_labels_counts = np.unique(cluster_labels, return_counts=True)
    print(cluster_values, cluster_labels_counts)
    
    medoids = []
    for i, cluster in enumerate(cluster_values):
      vdm_df_cluster = vdm_df.loc[vdm_df["cluster"]==cluster].drop("cluster", axis=1)
      df_cluster = df.loc[df["cluster"]==cluster]
      df_cluster = df_cluster.assign(cluster_count=cluster_labels_counts[i])
      medoid = getMedoidVDM(vdm_df_cluster, df_cluster, metric)
      #ith = 2
      #medoid = get_ith_medoid(vdm_df_cluster, df_cluster, metric, ith)
      medoids.append(medoid)
    medoids_df = pd.DataFrame(medoids)
    if target_class == "multi":
      print(f"******* sorting multi")
      medoids_df = medoids_df.sort_values(by='cluster', key=target_sorter)
      print(medoids_df)

    folder_path = f"{HC_base_path}{metric}{vars}/Medoids/"
    folder_exists = os.path.isdir(folder_path)
    # If folder doesn't exist, then create it.
    if not folder_exists:
        os.makedirs(folder_path)
        print("created folder : ", folder_path)

    medoids_paths = f"{folder_path}Medoids_{metric}_{target_class}.csv"
    medoids_df.to_csv(medoids_paths, index=False)

    folder_path = f"{radars_path}{metric}{vars}/Medoids/"
    folder_exists = os.path.isdir(folder_path)
    # If folder doesn't exist, then create it.
    if not folder_exists:
        os.makedirs(folder_path)
        print("created folder : ", folder_path)
    medoids_radar_paths = f"{folder_path}Medoids_{metric}_{target_class}.html"
    plot_all_medoids_radar(medoids_df.drop("cluster_count", axis=1), medoids_df["cluster_count"].values, save_path=medoids_radar_paths)

vars: 5 ...
******* target_class: multi
['Certainly not' 'Certainly yes' "Don't know/no answer"
 'Maybe yes maybe not' 'Probably not' 'Probably yes'] [2647 2781 2139 8042 5312 5684]
******* sorting multi
       InternetUsers  ...  cluster_count
5990        0.448276  ...           2647
12563       0.448276  ...           5312
12618       0.448276  ...           2139
2263        0.448276  ...           8042
2007        0.500000  ...           5684
19905       0.448276  ...           2781

[6 rows x 7 columns]
rows: 2, cols: 3
******* target_class: binary
******No more maybes
['Probably not' 'Certainly not' 'Probably yes' 'Certainly yes']
['NO' 'YES'] [7959 8465]
rows: 1, cols: 3
vars: 6 ...
******* target_class: multi
['Certainly not' 'Certainly yes' "Don't know/no answer"
 'Maybe yes maybe not' 'Probably not' 'Probably yes'] [2647 2781 2139 8042 5312 5684]
******* sorting multi
       InternetUsers  ...  cluster_count
5990        0.448276  ...           2647
12563       0.448276  ...   

## Test radar plots wrt target

In [101]:
metric = "VDM"
vars = 6
target_class = "multi"
medoids_paths = f"{HC_base_path}{metric}{vars}/Medoids/Medoids_{metric}_{target_class}.csv"
medoids_df = pd.read_csv(medoids_paths)
medoids_df

InternetUsers  ...  cluster_count
0       0.448276  ...           2647
1       0.448276  ...           5312
2       0.448276  ...           2139
3       0.448276  ...           8042
4       0.448276  ...           5684
5       0.500000  ...           2781

[6 rows x 8 columns]

In [102]:
metric = "VDM"
vars = 6
target_class = "multi"
medoids_paths = f"{HC_base_path}{metric}{vars}/Medoids2/Medoids_{metric}_{target_class}.csv"
medoids_df = pd.read_csv(medoids_paths)
medoids_df

InternetUsers  ...  cluster_count
0       0.448276  ...           2647
1       0.448276  ...           5312
2       0.741379  ...           2139
3       0.448276  ...           8042
4       0.500000  ...           5684
5       0.500000  ...           2781

[6 rows x 8 columns]

In [67]:
medoids_df.index[1]

1

In [68]:
medoids_df.drop(medoids_df.index[0]).index[0]

1

In [51]:
((medoids_df.InternetUsers == medoids_df.iloc[0].InternetUsers) &
                (medoids_df.Concern_environmental_impacts == medoids_df.iloc[0].Concern_environmental_impacts) &
                (medoids_df.Would_subsribe_car_sharing_if_available == medoids_df.iloc[0].Would_subsribe_car_sharing_if_available) &
                (medoids_df.Preference_tolls_or_traffic_limitation == medoids_df.iloc[0].Preference_tolls_or_traffic_limitation) &
                (medoids_df.Country == medoids_df.iloc[0].Country) &
                (medoids_df.Location_of_resudence == medoids_df.iloc[0].Location_of_resudence))

0     True
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [43]:
medoids_df

InternetUsers  ...  cluster_count
0       0.448276  ...           2647
1       0.448276  ...           5312
2       0.448276  ...           2139
3       0.448276  ...           8042
4       0.500000  ...           5684
5       0.500000  ...           2781

[6 rows x 8 columns]

In [ ]:
def target_sorter(column):
    """Sort function"""
    answers = ["Certainly not","Probably not", "Don't know/no answer",'Maybe yes maybe not',"Probably yes","Certainly yes"]
    correspondence = {answer: order for order, answer in enumerate(answers)}
    return column.map(correspondence)


In [ ]:
sorters = {
  "multi": ["Certainly not","Probably not", "Don't know/no answer",'Maybe yes maybe not',"Probably yes","Certainly yes"],
  "binary": ["NO", "YES"]
}
medoids_df = medoids_df.sort_values(by='cluster', key=tm_sorter)
medoids_df

InternetUsers  ...               cluster
0       0.448276  ...         Certainly not
4       0.448276  ...          Probably not
2       0.448276  ...  Don't know/no answer
3       0.448276  ...   Maybe yes maybe not
5       0.500000  ...          Probably yes
1       0.500000  ...         Certainly yes

[6 rows x 7 columns]